#!/usr/bin/env python3

import sys
from pathlib import Path
sys.tracebacklimit = 0

configfile: 'config.yaml'

print("Module-level cellranger job config:")
print(type(config), config)

rule run_cellranger:
    input: csv='DATA/{library}/libraries.csv'
    output: bam='DATA/{library}/CELLRANGER/possorted_genome_bam.bam'
    params:
        create_bam='true',
        transcriptome=config['transcriptome'],
        scratch='/lscratch/$SLURM_JOB_ID'
    conda: 'envs/requirements.yaml'
    script: 'scripts/cellranger.sh'
